export enum natureReclamation {
  SOLDE_COMPTE_INCORRECTE = 'SOLDE_COMPTE_INCORRECTE',
  MNT_INDEM_INCORRECTE = 'MNT_INDEM_INCORRECTE',
  DEPASSEMENT_DELAI_TRAITEMENT = 'DEPASSEMENT_DELAI_TRAITEMENT',
  DEPOT_EXCEP = 'DEPOT_EXCEP',
  QUALITE_RELATION_CLIENT = 'QUALITE_RELATION_CLIENT',
  AUTRE = 'AUTRE'
}
