export enum StatusCompte {
  STP = 'STP',
  NSTP= 'NSTP'
  // NOUVELLE_DEMANDE = 'NOUVELLE_DEMANDE',
  // EN_ATTENTE_DE_COMPLEMENT = 'EN_ATTENTE_DE_COMPLEMENT',
  // TRAITEE = 'TRAITEE',
  // APPROUVE = 'APPROUVE',
  // VALIDE_PAR_SGFG = 'VALIDE_PAR_SGFG',
  // REJETE_PAR_SGFG = 'REJETE_PAR_SGFG',
  // CLOTUREE = 'CLOTUREE',
  // BROUILLON = 'BROUILLON',
}


